[tool.poetry]
name = "ltunesradio"
version = "0.1.0"
description = ""
authors = ["LoganLatham1 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
